# Generated by Django 4.2.16 on 2026-03-06 00:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='挑战日期')),
                ('fen', models.CharField(max_length=255, verbose_name='初始 FEN')),
                ('target_description', models.TextField(blank=True, verbose_name='目标描述')),
                ('solution_moves', models.JSONField(default=list, verbose_name='正确解法序列')),
                ('max_moves', models.IntegerField(blank=True, null=True, verbose_name='最大步数限制')),
                ('time_limit', models.IntegerField(blank=True, null=True, verbose_name='时间限制（秒）')),
                ('difficulty', models.IntegerField(default=5, verbose_name='难度等级')),
                ('stars', models.IntegerField(default=3, verbose_name='星级')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='总挑战次数')),
                ('unique_players', models.IntegerField(default=0, verbose_name='参与人数')),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='完成率')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('puzzle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_challenges', to='puzzles.puzzle', verbose_name='关联残局')),
            ],
            options={
                'verbose_name': '每日挑战',
                'verbose_name_plural': '每日挑战',
                'db_table': 'daily_challenges',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeStreak',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('current_streak', models.IntegerField(default=0, verbose_name='当前连续天数')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='最长连续天数')),
                ('last_completion_date', models.DateField(blank=True, null=True, verbose_name='最后完成日期')),
                ('total_completions', models.IntegerField(default=0, verbose_name='总完成次数')),
                ('total_perfect', models.IntegerField(default=0, verbose_name='完美解法次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_streak', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '连续打卡记录',
                'verbose_name_plural': '连续打卡记录',
                'db_table': 'challenge_streaks',
                'indexes': [models.Index(fields=['user'], name='challenge_s_user_id_920ee8_idx'), models.Index(fields=['-current_streak'], name='challenge_s_current_37cf9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_fen', models.CharField(max_length=255, verbose_name='初始 FEN')),
                ('move_history', models.JSONField(default=list, verbose_name='走棋历史')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('timeout', '超时'), ('abandoned', '放弃')], default='success', max_length=20, verbose_name='状态')),
                ('moves_used', models.IntegerField(blank=True, null=True, verbose_name='使用步数')),
                ('time_used', models.IntegerField(blank=True, null=True, verbose_name='使用时间（秒）')),
                ('is_optimal', models.BooleanField(default=False, verbose_name='是否最优解')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('stars_earned', models.IntegerField(default=0, verbose_name='获得星级')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='尝试时间')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='daily_challenge.dailychallenge', verbose_name='挑战')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '挑战尝试',
                'verbose_name_plural': '挑战尝试',
                'db_table': 'challenge_attempts',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['challenge', 'user'], name='challenge_a_challen_346418_idx'), models.Index(fields=['-attempted_at'], name='challenge_a_attempt_146585_idx'), models.Index(fields=['-score'], name='challenge_a_score_aa5129_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='challengeattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('attempted_at__gte', django.db.models.expressions.CombinedExpression(models.F('attempted_at'), '-', models.Value(datetime.timedelta(days=1))))), fields=('user', 'attempted_at'), name='unique_user_daily_challenge'),
        ),
    ]
