# Generated by Django 4.2.28 on 2026-03-05 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='关卡名称')),
                ('description', models.TextField(blank=True, verbose_name='关卡描述')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='来源/名称')),
                ('fen_initial', models.TextField(verbose_name='初始 FEN 位置')),
                ('solution_moves', models.JSONField(help_text='正确走法序列 [{"from": "e2", "to": "e4", "piece": "P"}, ...]', verbose_name='解法序列')),
                ('difficulty', models.IntegerField(choices=[(1, '入门 (1 星)'), (2, '入门 (2 星)'), (3, '入门 (3 星)'), (4, '进阶 (4 星)'), (5, '进阶 (5 星)'), (6, '进阶 (6 星)'), (7, '高手 (7 星)'), (8, '高手 (8 星)'), (9, '大师 (9 星)'), (10, '大师 (10 星)')], verbose_name='难度等级 (1-10)')),
                ('move_limit', models.IntegerField(blank=True, null=True, verbose_name='步数限制')),
                ('time_limit', models.IntegerField(blank=True, null=True, verbose_name='时间限制 (秒)')),
                ('hint', models.TextField(blank=True, verbose_name='提示内容')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='总挑战次数')),
                ('total_completions', models.IntegerField(default=0, verbose_name='总通关次数')),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='通关率 (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'puzzles',
                'ordering': ['difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PuzzleProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_completed', models.IntegerField(default=0, verbose_name='总通关数')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='总挑战次数')),
                ('max_difficulty_passed', models.IntegerField(default=0, verbose_name='最高通过难度')),
                ('total_stars', models.IntegerField(default=0, verbose_name='总星级')),
                ('stars_1', models.IntegerField(default=0, verbose_name='1 星通关数')),
                ('stars_2', models.IntegerField(default=0, verbose_name='2 星通关数')),
                ('stars_3', models.IntegerField(default=0, verbose_name='3 星通关数')),
                ('ranking_points', models.IntegerField(default=0, verbose_name='排名积分')),
                ('completed_puzzle_ids', models.JSONField(default=list, verbose_name='已通关关卡 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'puzzle_progress',
            },
        ),
        migrations.CreateModel(
            name='PuzzleAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('success', '成功'), ('failed', '失败'), ('timeout', '超时'), ('abandoned', '放弃')], default='in_progress', max_length=20)),
                ('fen_current', models.TextField(verbose_name='当前 FEN 位置')),
                ('current_move_index', models.IntegerField(default=0, verbose_name='当前解法步骤')),
                ('move_history', models.JSONField(default=list, help_text='用户走棋记录 [{"from": "e2", "to": "e4", "piece": "P", "correct": true}, ...]', verbose_name='走棋历史')),
                ('moves_used', models.IntegerField(default=0, verbose_name='使用步数')),
                ('time_used', models.IntegerField(default=0, verbose_name='耗时 (秒)')),
                ('stars', models.IntegerField(blank=True, null=True, verbose_name='星级评价 (1-3)')),
                ('points_earned', models.IntegerField(default=0, verbose_name='获得积分')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='puzzles.puzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'puzzle_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['difficulty', 'is_active'], name='puzzles_difficu_5095f9_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['is_active', '-created_at'], name='puzzles_is_acti_060d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['total_completions'], name='puzzles_total_c_fab318_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzleprogress',
            index=models.Index(fields=['-ranking_points'], name='puzzle_prog_ranking_577f86_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzleprogress',
            index=models.Index(fields=['-total_completed'], name='puzzle_prog_total_c_cd82dc_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzleattempt',
            index=models.Index(fields=['user', 'status'], name='puzzle_atte_user_id_6c2335_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzleattempt',
            index=models.Index(fields=['puzzle', 'status'], name='puzzle_atte_puzzle__ca012f_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzleattempt',
            index=models.Index(fields=['user', 'puzzle'], name='puzzle_atte_user_id_de6006_idx'),
        ),
    ]
