# Generated by Django 4.2.16 on 2026-03-10 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('waiting', '等待中'), ('playing', '对局中'), ('finished', '已结束'), ('aborted', '已中止')], default='waiting', max_length=20, verbose_name='对局状态')),
                ('game_type', models.CharField(choices=[('ai', 'AI 对战'), ('match', '匹配对战'), ('friend', '好友对战'), ('custom', '自定义对局')], default='ai', max_length=20, verbose_name='对局类型')),
                ('current_player', models.CharField(choices=[('red', '红方'), ('black', '黑方')], db_column='turn', default='red', max_length=10, verbose_name='当前回合')),
                ('fen_start', models.TextField(blank=True, db_column='fen_start', default='rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1', null=True, verbose_name='初始棋盘状态')),
                ('fen_current', models.TextField(db_column='fen_current', default='rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1', verbose_name='当前棋盘状态')),
                ('winner', models.CharField(blank=True, choices=[('red', '红方'), ('black', '黑方'), ('draw', '和棋')], max_length=10, null=True, verbose_name='获胜方')),
                ('win_reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='获胜原因')),
                ('move_count', models.IntegerField(db_column='move_count', default=0, verbose_name='走棋次数')),
                ('timeout_seconds', models.IntegerField(db_column='time_control_base', default=7200, verbose_name='超时时间（秒）')),
                ('red_time_remaining', models.IntegerField(db_column='red_time_remaining', default=7200, verbose_name='红方剩余时间（秒）')),
                ('black_time_remaining', models.IntegerField(db_column='black_time_remaining', default=7200, verbose_name='黑方剩余时间（秒）')),
                ('last_move_time', models.DateTimeField(blank=True, db_column='last_move_time', null=True, verbose_name='最后走棋时间')),
                ('player_black', models.ForeignKey(blank=True, db_column='black_player_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL, verbose_name='黑方玩家')),
                ('player_red', models.ForeignKey(blank=True, db_column='red_player_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_red', to=settings.AUTH_USER_MODEL, verbose_name='红方玩家')),
            ],
            options={
                'verbose_name': '游戏对局',
                'verbose_name_plural': '游戏对局',
                'db_table': 'games',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RankingCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ranking_type', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('all_time', '总榜')], max_length=20)),
                ('cache_date', models.DateField(blank=True, null=True)),
                ('cache_week', models.IntegerField(blank=True, null=True)),
                ('cache_year', models.IntegerField(blank=True, null=True)),
                ('leaderboard_data', models.JSONField(default=list, help_text='排行榜数据 JSON')),
                ('total_players', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ranking_caches',
                'ordering': ['-cache_date', '-cache_week', '-cache_year'],
                'indexes': [models.Index(fields=['ranking_type', 'is_valid'], name='ranking_cac_ranking_434200_idx'), models.Index(fields=['ranking_type', 'cache_date', 'is_valid'], name='ranking_cac_ranking_911685_idx'), models.Index(fields=['ranking_type', 'cache_week', 'cache_year', 'is_valid'], name='ranking_cac_ranking_5b6dd1_idx')],
                'unique_together': {('ranking_type', 'cache_week', 'cache_year'), ('ranking_type',), ('ranking_type', 'cache_date')},
            },
        ),
        migrations.CreateModel(
            name='FriendRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_code', models.CharField(max_length=10, unique=True, verbose_name='房间号')),
                ('status', models.CharField(choices=[('waiting', '等待中'), ('playing', '对局中'), ('finished', '已结束'), ('expired', '已过期')], default='waiting', max_length=20, verbose_name='房间状态')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_friend_rooms', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friend_room', to='games.game', verbose_name='关联游戏')),
            ],
            options={
                'verbose_name': '好友对战房间',
                'verbose_name_plural': '好友对战房间',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.TextField(help_text='消息内容')),
                ('message_type', models.CharField(choices=[('text', '文本消息'), ('system', '系统消息'), ('emoji', '表情消息')], default='text', max_length=20)),
                ('room_type', models.CharField(choices=[('game', '对局房间'), ('spectator', '观战房间')], default='game', help_text='聊天房间类型', max_length=20)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(blank=True, help_text='关联的对局（对局聊天或观战聊天）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='games.game')),
                ('sender', models.ForeignKey(blank=True, help_text='消息发送者（系统消息为空）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRankingStats',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_games', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('total_draws', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('highest_score', models.IntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_win_streak', models.IntegerField(default=0)),
                ('longest_win_streak', models.IntegerField(default=0)),
                ('current_daily_rank', models.IntegerField(blank=True, null=True)),
                ('current_weekly_rank', models.IntegerField(blank=True, null=True)),
                ('current_all_time_rank', models.IntegerField(blank=True, null=True)),
                ('last_game_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_ranking_stats',
                'ordering': ['-total_score'],
                'indexes': [models.Index(fields=['-total_score'], name='user_rankin_total_s_fe4622_idx'), models.Index(fields=['-total_wins'], name='user_rankin_total_w_560ec8_idx'), models.Index(fields=['current_daily_rank'], name='user_rankin_current_48d25f_idx'), models.Index(fields=['current_weekly_rank'], name='user_rankin_current_8cfca2_idx'), models.Index(fields=['current_all_time_rank'], name='user_rankin_current_95e5c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Spectator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('watching', '观战中'), ('left', '已离开'), ('kicked', '被踢出')], default='watching', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='观战时长（秒）', null=True)),
                ('is_anonymous', models.BooleanField(default=False, help_text='是否匿名观战')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectators', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectated_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spectators',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['game', 'status'], name='spectators_game_id_0a7034_idx'), models.Index(fields=['user', 'status'], name='spectators_user_id_10d74d_idx'), models.Index(fields=['-joined_at'], name='spectators_joined__1417f7_idx')],
                'unique_together': {('game', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('game_type', models.CharField(choices=[('single', '单机'), ('online', '联网'), ('friend', '好友')], default='online', max_length=20)),
                ('result', models.CharField(choices=[('win', '胜利'), ('loss', '失败'), ('draw', '和棋')], max_length=10)),
                ('score_gained', models.IntegerField(default=0)),
                ('elo_change', models.IntegerField(default=0)),
                ('moves_made', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('is_rated', models.BooleanField(default=True)),
                ('game_date', models.DateField()),
                ('game_week', models.IntegerField()),
                ('game_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranking_record', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_ranking_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'game_date'], name='game_rankin_user_id_410ce5_idx'), models.Index(fields=['game_date'], name='game_rankin_game_da_809856_idx'), models.Index(fields=['game_week', 'game_year'], name='game_rankin_game_we_be7b29_idx'), models.Index(fields=['-score_gained'], name='game_rankin_score_g_fdaf2d_idx'), models.Index(fields=['user', 'result'], name='game_rankin_user_id_a0bbea_idx'), models.Index(fields=['is_rated', 'game_date'], name='game_rankin_is_rate_be2e86_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField(default=1, verbose_name='第几步')),
                ('color', models.CharField(choices=[('red', '红方'), ('black', '黑方')], default='red', max_length=10, verbose_name='颜色')),
                ('from_x', models.IntegerField(blank=True, null=True, verbose_name='起始 x 坐标')),
                ('from_y', models.IntegerField(blank=True, null=True, verbose_name='起始 y 坐标')),
                ('to_x', models.IntegerField(blank=True, null=True, verbose_name='目标 x 坐标')),
                ('to_y', models.IntegerField(blank=True, null=True, verbose_name='目标 y 坐标')),
                ('piece_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='棋子类型')),
                ('move_time', models.DateTimeField(auto_now_add=True, verbose_name='走棋时间')),
                ('time_taken', models.FloatField(blank=True, null=True, verbose_name='走棋用时（秒）')),
                ('fen_after', models.TextField(blank=True, null=True, verbose_name='走棋后棋盘状态')),
                ('is_capture', models.BooleanField(default=False, verbose_name='是否吃子')),
                ('is_check', models.BooleanField(default=False, verbose_name='是否将军')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.game', verbose_name='游戏对局')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_moves', to=settings.AUTH_USER_MODEL, verbose_name='走棋玩家')),
            ],
            options={
                'verbose_name': '走棋记录',
                'verbose_name_plural': '走棋记录',
                'ordering': ['move_number'],
                'indexes': [models.Index(fields=['game', 'move_number'], name='games_gamem_game_id_348bce_idx'), models.Index(fields=['player'], name='games_gamem_player__64ed8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建对局'), ('start', '开始对局'), ('move', '走棋'), ('abort', '中止对局'), ('auto_abort', '自动中止'), ('finish', '结束对局'), ('mark_abnormal', '标记异常'), ('unmark_abnormal', '取消异常标记'), ('join', '加入对局'), ('leave', '离开对局'), ('spectator_join', '观战者加入'), ('spectator_leave', '观战者离开'), ('chat_message', '聊天消息'), ('other', '其他操作')], max_length=50, verbose_name='操作类型')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='操作详情')),
                ('severity', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], default='info', max_length=20, verbose_name='严重程度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='games.game', verbose_name='游戏对局')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '游戏日志',
                'verbose_name_plural': '游戏日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['game', '-created_at'], name='games_gamel_game_id_7f7d47_idx'), models.Index(fields=['operator', '-created_at'], name='games_gamel_operato_9d10a0_idx'), models.Index(fields=['action', '-created_at'], name='games_gamel_action_2ed16a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-created_at'], name='games_created_6c51f6_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status'], name='games_status_def24c_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['player_red'], name='games_red_pla_49b2db_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['player_black'], name='games_black_p_74340a_idx'),
        ),
        migrations.AddIndex(
            model_name='friendroom',
            index=models.Index(fields=['room_code'], name='games_frien_room_co_14b78b_idx'),
        ),
        migrations.AddIndex(
            model_name='friendroom',
            index=models.Index(fields=['status'], name='games_frien_status_1e93be_idx'),
        ),
        migrations.AddIndex(
            model_name='friendroom',
            index=models.Index(fields=['creator'], name='games_frien_creator_4eb3de_idx'),
        ),
        migrations.AddIndex(
            model_name='friendroom',
            index=models.Index(fields=['expires_at'], name='games_frien_expires_fe1df0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['game', 'room_type', '-created_at'], name='chat_messag_game_id_a4568f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', '-created_at'], name='chat_messag_sender__5f8b49_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_uuid'], name='chat_messag_message_8fcbab_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_deleted', '-created_at'], name='chat_messag_is_dele_1d4674_idx'),
        ),
    ]
