# Generated by Django 4.2.28 on 2026-03-03 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_type', models.CharField(choices=[('single', '单机'), ('online', '联网'), ('friend', '好友')], default='single', max_length=20)),
                ('status', models.CharField(choices=[('pending', '等待开始'), ('playing', '进行中'), ('red_win', '红方胜'), ('black_win', '黑方胜'), ('draw', '和棋'), ('aborted', '已取消')], default='pending', max_length=20)),
                ('fen_start', models.TextField()),
                ('fen_current', models.TextField()),
                ('turn', models.CharField(default='w', max_length=5)),
                ('winner', models.CharField(blank=True, choices=[('red', '红方'), ('black', '黑方'), ('draw', '和棋')], max_length=10, null=True)),
                ('win_reason', models.CharField(blank=True, help_text='获胜原因：checkmate, resign, timeout, agreement', max_length=50, null=True)),
                ('time_control_base', models.IntegerField(default=600)),
                ('time_control_increment', models.IntegerField(default=0)),
                ('red_time_remaining', models.IntegerField(default=600)),
                ('black_time_remaining', models.IntegerField(default=600)),
                ('ai_level', models.IntegerField(blank=True, null=True)),
                ('ai_side', models.CharField(blank=True, max_length=5, null=True)),
                ('move_count', models.IntegerField(default=0)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('is_rated', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_games', to=settings.AUTH_USER_MODEL)),
                ('red_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'games',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameMove',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('move_number', models.IntegerField()),
                ('piece', models.CharField(max_length=1)),
                ('from_pos', models.CharField(max_length=3)),
                ('to_pos', models.CharField(max_length=3)),
                ('captured', models.CharField(blank=True, max_length=1, null=True)),
                ('is_check', models.BooleanField(default=False)),
                ('is_capture', models.BooleanField(default=False)),
                ('notation', models.CharField(blank=True, max_length=10, null=True)),
                ('san', models.CharField(blank=True, max_length=10, null=True)),
                ('fen_after', models.TextField()),
                ('time_remaining', models.IntegerField(blank=True, null=True)),
                ('time_used', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.game')),
            ],
            options={
                'db_table': 'game_moves',
                'ordering': ['move_number'],
                'indexes': [models.Index(fields=['game', 'move_number'], name='game_moves_game_id_2e676a_idx'), models.Index(fields=['piece'], name='game_moves_piece_08bc38_idx')],
                'unique_together': {('game', 'move_number')},
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status'], name='games_status_def24c_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['red_player', 'status'], name='games_red_pla_1f2bed_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['black_player', 'status'], name='games_black_p_aed5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-created_at'], name='games_created_6c51f6_idx'),
        ),
    ]
