# Generated by Django 4.2.16 on 2026-03-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_rated',
            field=models.BooleanField(default=False, verbose_name='是否计分'),
        ),
    ]
