# Generated by Django 4.2.28 on 2026-03-10 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_game_is_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='undo_count_black',
            field=models.IntegerField(default=0, verbose_name='黑方已用悔棋次数'),
        ),
        migrations.AddField(
            model_name='game',
            name='undo_count_red',
            field=models.IntegerField(default=0, verbose_name='红方已用悔棋次数'),
        ),
        migrations.AddField(
            model_name='game',
            name='undo_limit',
            field=models.IntegerField(default=3, verbose_name='悔棋次数限制'),
        ),
        migrations.CreateModel(
            name='UndoRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
                ('undo_count', models.IntegerField(default=1, verbose_name='悔棋步数')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('auto', '自动通过')], default='pending', max_length=20, verbose_name='状态')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='响应时间')),
                ('auto_accept_at', models.DateTimeField(blank=True, null=True, verbose_name='自动接受时间')),
                ('reason', models.TextField(blank=True, default='', verbose_name='悔棋原因')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undo_requests', to='games.game', verbose_name='游戏对局')),
                ('move_to_undo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='undo_requests', to='games.gamemove', verbose_name='要撤销的走棋')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undo_requests', to=settings.AUTH_USER_MODEL, verbose_name='请求者')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undo_responses', to=settings.AUTH_USER_MODEL, verbose_name='响应者')),
            ],
            options={
                'verbose_name': '悔棋记录',
                'verbose_name_plural': '悔棋记录',
                'db_table': 'games_undo_request',
                'ordering': ['-requested_at'],
            },
        ),
    ]
