# Generated by Django 4.2.28 on 2026-03-10 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0003_game_undo_count_black_game_undo_count_red_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameShare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('share_token', models.CharField(max_length=64, unique=True, verbose_name='分享令牌')),
                ('share_type', models.CharField(choices=[('public', '公开分享'), ('private', '私密分享'), ('link', '链接分享')], default='public', max_length=20, verbose_name='分享类型')),
                ('share_password', models.CharField(blank=True, default='', max_length=20, verbose_name='分享密码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.TextField(blank=True, default='', verbose_name='分享说明')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='games.game', verbose_name='游戏对局')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_shares', to=settings.AUTH_USER_MODEL, verbose_name='分享者')),
            ],
            options={
                'verbose_name': '棋局分享',
                'verbose_name_plural': '棋局分享',
                'db_table': 'games_share',
                'ordering': ['-created_at'],
            },
        ),
    ]
