# Generated by Django 4.2.28 on 2026-03-03 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('season_number', models.IntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seasons',
                'ordering': ['-season_number'],
                'indexes': [models.Index(fields=['is_active'], name='seasons_is_acti_2e3a86_idx'), models.Index(fields=['start_date', 'end_date'], name='seasons_start_d_c59787_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerRank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('rating', models.IntegerField(default=1500)),
                ('segment', models.CharField(choices=[('bronze', '青铜'), ('silver', '白银'), ('gold', '黄金'), ('platinum', '铂金'), ('diamond', '钻石'), ('master', '大师')], default='bronze', max_length=20)),
                ('season_id', models.IntegerField(default=1)),
                ('total_games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('peak_rating', models.IntegerField(default=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'player_ranks',
                'ordering': ['-rating'],
                'indexes': [models.Index(fields=['user_id'], name='player_rank_user_id_a916d1_idx'), models.Index(fields=['segment', '-rating'], name='player_rank_segment_d14d7f_idx'), models.Index(fields=['season_id', '-rating'], name='player_rank_season__ee4b88_idx'), models.Index(fields=['-rating'], name='player_rank_rating_5bd6e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('game_type', models.CharField(default='online', max_length=50)),
                ('rating', models.IntegerField(default=1500)),
                ('search_range', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('searching', '搜索中'), ('matched', '已匹配'), ('cancelled', '已取消'), ('timeout', '超时')], default='searching', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('opponent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('game_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'match_queues',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='match_queue_user_id_3c08b0_idx'), models.Index(fields=['game_type', 'status'], name='match_queue_game_ty_eb293b_idx'), models.Index(fields=['rating'], name='match_queue_rating_9b212c_idx'), models.Index(fields=['created_at'], name='match_queue_created_15144c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('opponent_id', models.CharField(max_length=255)),
                ('game_id', models.UUIDField()),
                ('user_rating', models.IntegerField()),
                ('opponent_rating', models.IntegerField()),
                ('rating_change', models.IntegerField(default=0)),
                ('result', models.CharField(choices=[('win', '胜利'), ('loss', '失败'), ('draw', '和棋')], max_length=10)),
                ('match_duration', models.IntegerField(blank=True, help_text='匹配耗时（秒）', null=True)),
                ('queue_time', models.IntegerField(blank=True, help_text='排队耗时（秒）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'match_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='match_histo_user_id_a5469e_idx'), models.Index(fields=['game_id'], name='match_histo_game_id_3b6389_idx'), models.Index(fields=['result'], name='match_histo_result_222127_idx'), models.Index(fields=['created_at'], name='match_histo_created_f174ac_idx')],
            },
        ),
    ]
