# Generated by Django 4.2.28 on 2026-03-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchqueue',
            name='status',
            field=models.CharField(choices=[('waiting', '等待中'), ('searching', '搜索中'), ('matched', '已匹配'), ('cancelled', '已取消'), ('timeout', '超时')], default='searching', max_length=20),
        ),
    ]
