# Generated by Django 4.2.28 on 2026-03-03 04:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='难度等级 (1-10)', unique=True)),
                ('name', models.CharField(help_text='难度名称', max_length=50)),
                ('description', models.TextField(blank=True, help_text='难度描述')),
                ('skill_level', models.IntegerField(help_text='Stockfish Skill Level (0-20)')),
                ('search_depth', models.IntegerField(help_text='搜索深度')),
                ('think_time_ms', models.IntegerField(help_text='思考时间（毫秒）')),
                ('move_overhead', models.IntegerField(default=100, help_text='移动开销（毫秒）')),
                ('threads', models.IntegerField(default=2, help_text='线程数')),
                ('hash_mb', models.IntegerField(default=128, help_text='哈希表大小（MB）')),
                ('elo_estimate', models.IntegerField(help_text='预估 Elo 分数')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_difficulties',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='AIGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_id', models.UUIDField(help_text='玩家 ID')),
                ('ai_level', models.IntegerField(help_text='AI 难度等级 (1-10)')),
                ('ai_side', models.CharField(choices=[('red', '红方'), ('black', '黑方')], help_text='AI 执棋方', max_length=5)),
                ('fen_start', models.TextField(help_text='初始 FEN')),
                ('fen_current', models.TextField(help_text='当前 FEN')),
                ('move_history', models.JSONField(default=list, help_text='走棋历史记录')),
                ('status', models.CharField(choices=[('pending', '等待开始'), ('playing', '进行中'), ('red_win', '红方胜'), ('black_win', '黑方胜'), ('draw', '和棋'), ('aborted', '已取消')], default='pending', help_text='对局状态', max_length=20)),
                ('winner', models.CharField(blank=True, choices=[('red', '红方'), ('black', '黑方'), ('draw', '和棋')], help_text='获胜方', max_length=10, null=True)),
                ('total_moves', models.IntegerField(default=0, help_text='总步数')),
                ('avg_think_time_ms', models.IntegerField(blank=True, help_text='AI 平均思考时间', null=True)),
                ('max_think_time_ms', models.IntegerField(blank=True, help_text='AI 最大思考时间', null=True)),
                ('avg_search_depth', models.IntegerField(blank=True, help_text='AI 平均搜索深度', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_games',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fen', models.TextField(help_text='FEN 字符串')),
                ('move_number', models.IntegerField(help_text='第几步')),
                ('evaluation_score', models.FloatField(help_text='评估分数')),
                ('evaluation_text', models.CharField(help_text='评估文字描述', max_length=50)),
                ('best_move', models.CharField(help_text='最佳走棋', max_length=10)),
                ('search_depth', models.IntegerField(help_text='搜索深度')),
                ('top_moves', models.JSONField(default=list, help_text='顶级走法列表')),
                ('thinking_time_ms', models.IntegerField(help_text='思考时间（毫秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(blank=True, help_text='关联的 AI 对局', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='ai_engine.aigame')),
            ],
            options={
                'db_table': 'ai_analyses',
                'ordering': ['move_number'],
            },
        ),
    ]
