# Generated by Django 4.2.28 on 2026-03-05 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aigame',
            name='player_id',
        ),
        migrations.AddField(
            model_name='aigame',
            name='player',
            field=models.ForeignKey(blank=True, help_text='玩家', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
